# Generated by Django 5.2.17 on 2026-08-07 06:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='uploads/')),
                ('result_image', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('result_original', models.ImageField(blank=True, null=True, upload_to='results/')),
                ('status', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('processing', 'Processing')], default='processing', max_length=16)),
                ('defects_found', models.IntegerField(default=0)),
                ('total_detections', models.IntegerField(default=0)),
                ('max_confidence', models.FloatField(default=0.0)),
                ('inference_mode', models.CharField(default='', max_length=64)),
                ('chip_bbox', models.CharField(blank=True, max_length=64, null=True)),
                ('summary_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DetectedDefect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_id', models.IntegerField()),
                ('label', models.CharField(max_length=64)),
                ('confidence', models.FloatField()),
                ('bbox', models.CharField(max_length=128)),
                ('severity', models.CharField(default='unknown', max_length=32)),
                ('description', models.TextField(blank=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_defects', to='scanner.inspection')),
            ],
        ),
    ]
